import type { NextPage, NextPageContext } from 'next';
import Image from 'next/image';
import Head from 'next/head';

import { authentication } from '../lib/utils/authentication';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </>
  );
};

export const getServerSideProps = async (ctx: NextPageContext) => {
  const auth = authentication(ctx);

  if (!auth) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    };
  }

  return {
    props: {
      session: auth
    }
  };
};

export default Home;
